---
title       : Marsh Elevation Summary
subtitle    : Surface Elevation and Surface Accretion
author      : Adam Starke 
job         : Quick summary
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
widgets     : [nvd3]            # {mathjax, quiz, bootstrap}
mode        : standalone # {standalone, draft}

---
```{r Setup, include=FALSE, echo=FALSE}
require(Hmisc)
require(xtable)
require(knitr)
require(ggplot2)
require(ggthemes)
require(plyr)
require(scales)
require(ggmap)
require(slidify)
require(rCharts)

options(RCHART_WIDTH = 800, RCHART_HEIGHT = 500)

knitr::opts_chunk$set(comment= NA, results= 'asis')

load(".RData")


# Pulls in scripts(chunks) for creating tables and figures used within this document. The scripts/chunks are id-ed by the "@"-CodeChunkName at the start of each script. The following chunks are used in the document.
```

## Impetus of our work
>We are interested in the function and ulimately the fate of salt marshes on Long Island (and elsewhere of course)
>Need an 'easy' way to monitor
<
```{r echo = TRUE, results ='asis', message = FALSE}


```

--- .class #id 

## rCharts at work

```{r results='asis', comment=NA, message=FALSE, echo=FALSE}

stationSE <- nPlot(Date ~ Raw, group= 'Position_ID', data= SET.data.M, type= 'scatterChart')
stationSE
```


